### PR TITLE
Create pt.json

### PR DESCRIPTION
**Pull request by ViPeR5000**

### CODE REVIEW

**Review by nimroddolev — COMMENTED** [review]
Hi @ViPeR5000. Thank you so much or the contribution. The translation you provided is for the onboarding flow, which was only used in earlier versions of the integration. It is now no longer used.
In last month's HA release, 2023.8 support was added for translating the labels and descriptions used in the services.yaml file. I plan to add support for this in an upcoming release.
Thanks again!

**Comment by nimroddolev** [comment]
Hi @ViPeR5000.  I have released a new beta version (v0.7.3-beta3) which supports translations for the Chime TTS 'say' and 'clear_cache' services.

The integration's [en.json](https://github.com/nimroddolev/chime_tts/blob/14f0d3c499b65d7d3d52ae4e0110f5282b653af2/custom_components/chime_tts/translations/en.json) file includes all texts used and can serve as a template for other languages. It would be great if you could contribute translations for Portuguese!

To install/test the beta from HACS:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option
1. Select version `v0.7.3-beta3` from the updated version drop-down list

**Comment by ViPeR5000** [comment]
i will do that =)

**Review by nimroddolev — CHANGES_REQUESTED** [review]
The text referred to is obsolete. Please refer to the current en.json texts file for the current text values that can be translated.

**Pull request closed without merging**
